#instalar o loadbalance MetalLB, nao precisa se for implantar numa cloud, seguindo os passos: https://metallb.universe.tf/installation/
#kubectl edit configmap -n kube-system kube-proxy e setar o strictARP para true
#apiVersion: kubeproxy.config.k8s.io/v1alpha1
#kind: KubeProxyConfiguration
#mode: "ipvs"
#ipvs:
#  strictARP: true  <------- SETAR PARA TRUE
#kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.3/manifests/namespace.yaml
#kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.3/manifests/metallb.yaml
#kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:      
      - 35.232.143.67-35.232.143.67
      - 35.223.53.123-35.223.53.123
      - 35.239.214.48-35.239.214.48
